<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Question;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function createQuestion(string $questionName) {
        $entityManager = $this->getEntityManager();

        $question = new Question();
        $question->setName($questionName);

        $entityManager->persist($question);;

        return $question;
    }

    public function loadQuestionsByRegular(string $regular){
        return $this->createQueryBuilder("q")
            ->where('q.name LIKE :regular')
            ->setParameter("regular",$regular."%")
            ->setMaxResults(5)
            ->getQuery()
            ->getResult();
    }
}
