<?php

namespace AppBundle\Repository;

/**
 * StartedQuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StartedQuizRepository extends \Doctrine\ORM\EntityRepository
{

}
