<?php

namespace AppBundle\Repository;

/**
 * UserAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
