<?php

namespace AppBundle\Repository;

/**
 * WiredQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WiredQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
